INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Uma saga espacial onde você, como o Comandante Shepard, lidera uma equipe para salvar a galáxia de uma ameaça alienígena, moldando a história com suas escolhas.', 'Uma saga grandiosa de ficção científica que coloca você no papel do Comandante Shepard, um herói moldado pelas suas escolhas. Ao longo dos três jogos – Mass Effect 1, 2 e 3 – você enfrenta ameaças cósmicas, constrói alianças com diversas raças extraterrestres e toma decisões éticas que têm impacto duradouro no destino da galáxia . Combinando exploração interplanetária, combate tático em equipe e desenvolvimento de personagens profundos, a trilogia oferece centenas de horas de narrativa envolvente e ramificada, em que cada diálogo, relacionamento e perda importa. Uma experiência cinematográfica e emocional que continua sendo referência nos RPGs modernos.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Uma épica jornada no Velho Oeste, onde Arthur Morgan, membro da gangue Van der Linde, enfrenta o declínio da era dos fora-da-lei em um mundo aberto vasto e vivo.', 'Um épico dramático ambientado em 1899, quando o Velho Oeste entra em decadência. Você assume o papel de Arthur Morgan, membro da gangue Van der Linde, e vivencia seu dilema moral em meio à transição entre uma vida fora da lei e a chegada de um mundo moderno. A narrativa se destaca pela profundidade emocional de Arthur — um homem complexo, leal, mas dividido entre a lealdade à gangue e sua própria consciência — e pelos personagens que o rodeiam, cada um refletindo aspectos do fim de uma era. O jogo oferece um mundo aberto incrivelmente detalhado, com centenas de animações e atividades — desde caça, pesca e acampamentos, até interações espontâneas com NPCs que humanizam a jornada . A atenção aos pequenos gestos — como um sonho com um cervo, chuva ou trovoadas — acentua o tom melancólico e reflexivo da história . No fim, Red Dead Redemption 2 não é apenas sobre ação: é sobre identidade, mudança e o peso das escolhas no crepúsculo de um mundo que estava desaparecendo.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Jogue como Geralt de Rívia em uma aventura sombria e complexa repleta de escolhas morais, monstros aterrorizantes e intrigas políticas em um mundo aberto riquíssimo.', 'The Witcher 3 é um RPG de mundo aberto aclamado que coloca o jogador no papel de Geralt de Rívia, um caçador de monstros em busca de sua filha adotiva, Ciri, enquanto foge da ameaçadora Caçada Selvagem. Ambientado em um universo sombrio e cheio de escolhas morais complexas, o jogo combina combate com espada, magia e alquimia. Seu mundo é riquíssimo em conteúdo, repleto de missões secundárias bem escritas e personagens memoráveis. Com narrativa madura, trilha sonora marcante e duas expansões excelentes, é considerado um dos maiores jogos da história dos RPGs modernos.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Um intenso jogo de ação e stealth da FromSoftware, onde você controla um guerreiro shinobi em busca de vingança, enfrentando inimigos brutais em um Japão feudal reimaginado.', 'Num Japão feudal reimaginado, você assume o papel de Wolf, um shinobi marcado e fiel protetor do jovem senhor Kuro. Após uma tentativa de assassinato, Wolf embarca em uma jornada violenta para resgatar Kuro, enfrentando a clã Ashina e surgindo com habilidade única: a habilidade de ressuscitar após a morte — um ponto central nas mecânicas que mesclam narrativa e gameplay. Os combates exigem precisão cirúrgica, postura e agressividade, refletindo os temas de honra, ciclo de renascimento e escolhas morais. Ambientado em paisagens claras, pesadas e artísticas, Sekiro oferece uma experiência intensa e meditativa, que ressoa além da dificuldade.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Um conto cinematográfico de honra e sacrifício, em que Jin Sakai desafia tradições samurais para proteger sua terra da invasão mongol na ilha de Tsushima.', 'Na ilha de Tsushima, em 1274, o samurai Jin Sakai deve escolher entre seguir o código tradicional ou adotar métodos furtivos para defender seu povo dos invasores mongóis. A jornada envolve duelos filosóficos sobre honra, sacrifício e necessidade, enquanto Jin evolui de samurai idealista a “Fantasma” determinado a salvar Tsushima. O jogo apresenta paisagens cinematográficas inspiradas por filmes de Kurosawa, um mundo aberto detalhado e mecânicas dinâmicas de combate, arco narrativo envolvente e narração ambiental sofisticada, com trilha sonora e modo fotográfico que enaltecem a ambientação poética e visceral.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Mario embarca em uma jornada clássica por Dinosaur Land para salvar a Princesa Peach, explorando fases coloridas, montado em Yoshi e enfrentando o vilão Bowser.', 'Um marco atemporal dos videogames, onde Mario (ou Luigi) explora a vibrante Dinosaur Land para resgatar a Princesa Peach do vilão Bowser. Com um design de fases perfeito, cheia de saídas secretas, power-ups criativos (como a capa voadora) e a introdução do inconfundível Yoshi, o jogo equilibra desafio e diversão com elegância. O mundo interconectado permite múltiplas rotas, incentivando a descoberta e a rejogabilidade. Cada nível oferece um equilíbrio entre aprendizado gradual e mecânicas emocionantes, deixando claro por que é considerado referência em level design.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Um metroidvania desafiador e atmosférico em que você explora as profundezas de Hallownest, enfrentando criaturas sombrias em uma aventura de precisão e mistério.', 'Um metroidvania sombrio ambientado em Hallownest, um reino subterrâneo habitado por insetos afetados por uma Infecção misteriosa. Você controla o Knight, um ser silencioso e aparentemente fraco no início, resignado a explorar cavernas esquecidas, enfrentar criaturas agressivas e desvendar segredos escondidos. Conforme progride, novos movimentos — como o dash ou a capa Mothwing — permitem revisitar áreas, revelando que cada canto do mapa guarda uma história ou desafio renovado. A arte desenhada à mão e a trilha sonora melancólica criam uma atmosfera tensa e imersiva , enquanto a dificuldade desafia o jogador a aprender padrões de inimigos e vencer chefes exigentes. Hollow Knight cresce em camadas: cada nova habilidade ou área expande significativamente sua compreensão do mundo — e do próprio personagem. Um jogo que exige disciplina e atenção, mas recompensa com histórias sussurradas nas paredes antigas de Hallownest e uma experiência emocional gratificante.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Uma tocante e deslumbrante aventura de plataforma com elementos de metroidvania, onde Ori precisa restaurar a floresta de Nibel através de desafios emocionantes.', 'Uma jornada emocional ambientada na moribunda floresta de Nibel, onde você controla Ori, um pequeno espírito guardião. Após uma tempestade devastadora, Ori precisa restaurar os elementos da floresta – Água, Calor e Vento – resgatando seres queridos enquanto enfrenta desafios de plataforma e metroidvania. Com gráficos pintados à mão, trilha sonora comovente e narrativa poderosa sobre sacrifício e esperança, o jogo combina ação e exploração de forma harmoniosa. O sistema de “Soul Links” adiciona tensão e estratégia, levando o jogador a refletir sobre sacrifício e perseverança.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Um jogo de ação e plataforma com visual retrô dos anos 1930, onde Cuphead e Mugman enfrentam chefes intensos em um pacto com o diabo.', 'Inspirado em desenhos animados dos anos 1930, Cuphead é uma aventura run‑and‑gun focada em batalhas intensas contra chefes elaborados. Você controla Cuphead (e Mugman em modo co‑op) em uma missão para pagar uma dívida com o Diabo, coletando contratos de almas em fazendas peculiares e teatros macabros. Cada frame é desenhado à mão, com animação cel vibrantemente fluida, e o estilo artístico homenageia o surrealismo e o humor negro daquela era. O foco nas lutas exige reflexos rápidos e leitura de padrões, enquanto a história traz uma sátira espirituosa sobre apostas e redenção moral.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Sonic viaja no tempo para impedir os planos do Dr. Robotnik em um dos jogos mais estilizados da era clássica, com trilhas icônicas e fases dinâmicas.', 'Neste clássico da era Sega CD, Sonic enfrenta o Dr. Robotnik em Little Planet, um corpo celeste preso no tempo. Ao longo dos níveis, o ouriço viaja entre presente e futuro, alterando o destino das fases — onde ações no presente afetam o futuro do planeta. O jogo introduz personagens icônicos como Amy Rose e Metal Sonic, possui cinematics de animação expressivas e trilhas sonoras fenomenais (variando conforme as regiões). Uma mistura de velocidade, exploração temporal e design inspirado em narrativa visual, estabelecendo padrão para jogos com múltiplos finais.');

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);